### ISSUE TITLE
Error please remove it

### ISSUE THREAD

**Issue by paramikoooo** [resilar/psyscall#3]
Error please remove it

**Comment by resilar** [comment]
Only dynamic binaries are supported by psyscall.

> I can mmap memory to process , but how can I insert data to that memory?

Open a file descriptor to a file containing the data, and then read from
it into the address returned by mmap. Alternatively, you could use the
`fildes` parameter of mmap to directly map the data from the file to the
memory without reading (see the man pages for more information).
